### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by diogomqbm** [t10d/cra-template-kingdom#1]
# Description
Here we should agree on a common theming configuration for our boilerplate. Currently, we're mostly using [chakra-ui](https://chakra-ui.com/) and [theme-ui](https://theme-ui.com/) which are both very specific and uses [emotion](https://emotion.sh/docs/introduction) under the hood. That being said, we should choose which approach are we going to follow here. What do you guys think?

**Comment by leonardomolinan** [comment]
Until now I just worked with `theme-ui` and I like it, but I think we can give a chance to `chakra-ui`, since it was made inspired on `theme-ui`. Its more **robust**, and I see "more robust" as "more generic", and it can bring more flexibility to the Boilerplate.

**Comment by GuilhermeLLS** [comment]
I feel like I can't contributte much to this one. I've never used a CSS/UI framework beside tailwind-css (after a bit, I started liking it).

**Comment by diogomqbm** [comment]
I'd really appreciate using emotion because we could interop it with rescript using [bs-css](https://github.com/reasonml-labs/bs-css) 😅. But I'm ok if we end up choosing chakra.

**Comment by luisrondow** [comment]
I think `chakra-ui` is the best UI lib that we have. But we can discussed the pro and cons of using UI libs.

**Comment by marianaks** [comment]
It seems that most of us agree on using Chakra UI. I'll just left my 2cents about it.

So far, I think it's really useful and improves performance (I'm currently working on a project using chakra-ui and another with plain CSS, and this opinion is based only on my own experience). I haven't worked with theme-ui, so I can't make a good parallel with it, but just with I've seen, I still prefer chakra-ui. Maybe @phenrique7 can talk more about it, since he has worked with both.

Regarding the pros and cons of using an ui lib, I don't see any relevant cons. I would like to read what you, @luisrondow, think about it (your comment made me curious). It is a good question, what are the cons that can make us choose not to use a ui lib?

**Comment by diogomqbm** [comment]
Closed by #7. But you guys can continue discussing this here. Just saying we implemented chakra-ui since it was most voted option.

**Comment by diogomqbm** [comment]
In fact, I'm going to close this, and we can open a discussion on this topic on the future
