### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by diogomqbm** [t10d/cra-template-kingdom#15]
# Description
Same approach as #14 but for a register screen where the user should be able to create an account.

**Comment by phenrique7** [comment]
I was wondering if this functionality is really necessary for the template. My conclusion is that it is not necessary. I believe that this register part makes more sense within a Next.js template, for example, where we would have a context of use more focused on the "public". Generally in a SPA, access to the application is restricted to a specific group of users previously registered in the application, since the web app is more geared towards contexts of use internal to the organization's business. What do you think?

**Comment by diogomqbm** [comment]
I agree. I think we should have the first release and then open a discussion for more features like this one.
